# Generated by Django 2.1.1 on 2018-10-25 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Please enter first name.', max_length=50)),
                ('last_name', models.CharField(help_text='Please enter last name.', max_length=50)),
                ('sex', models.IntegerField(choices=[(0, 'male'), (1, 'female')], default=0, help_text='Please enter male or female', null=True)),
                ('age', models.IntegerField(help_text='Please enter age witch is between 0 and 120.', null=True)),
                ('profession', models.CharField(blank=True, help_text='Please enter your profession.', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter post title', max_length=100)),
                ('postDate', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(help_text='Enter your content of blog.', max_length=20000)),
                ('blogger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Blogger')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Please enter your comment', max_length=300)),
                ('comment_datetime', models.DateTimeField(auto_now_add=True)),
                ('blogPost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.BlogPost')),
                ('commenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Blogger')),
            ],
            options={
                'ordering': ['-comment_datetime'],
            },
        ),
    ]
